name: Update README Contribution Graph

on:
  schedule:
    - cron: '*/1 * * * *' # Her 1 dakikada bir çalışır
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Graph Type Based on Day
        id: graph
        run: |
          DAY=$(date +%d)
          if [ $((DAY % 2)) -eq 0 ]; then
            echo "GRAPH=snake" >> $GITHUB_ENV
          else
            echo "GRAPH=pacman" >> $GITHUB_ENV
          fi

      - name: Replace Graph in README
        run: |
          if [[ "$GRAPH" == "snake" ]]; then
            GRAPH_TAG='<img alt="snake contribution graph" src="https://raw.githubusercontent.com/YigitCittan/YigitCittan/output/github-contribution-grid-snake.svg">'
          else
            GRAPH_TAG='<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/YigitCittan/YigitCittan/output/pacman-contribution-graph-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/YigitCittan/YigitCittan/output/pacman-contribution-graph.svg">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/YigitCittan/YigitCittan/output/pacman-contribution-graph.svg">
</picture>'
          fi

          awk -v graph="$GRAPH_TAG" '
            BEGIN { in_section=0 }
            /<!-- GRAPH_START -->/ { print; in_section=1; print graph; next }
            /<!-- GRAPH_END -->/ { in_section=0 }
            !in_section
          ' README.md > temp.md && mv temp.md README.md

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update contribution graph to $GRAPH" || echo "No changes to commit"
          git push
